"""create alerts and analyses tables

Revision ID: c034ee325edf
Revises: 
Create Date: 2026-04-07 05:05:29.435598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c034ee325edf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('wazuh_id', sa.String(length=255), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('normalized_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('rule_id', sa.String(length=50), nullable=False),
    sa.Column('rule_description', sa.Text(), nullable=False),
    sa.Column('agent_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ANALYZING', 'COMPLETED', 'FAILED', name='alert_status', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wazuh_id')
    )
    op.create_table('analyses',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('alert_id', sa.UUID(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('hypothesis', sa.Text(), nullable=False),
    sa.Column('possible_causes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('key_indicators', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('recommended_checks', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence_note', sa.Text(), nullable=False),
    sa.Column('raw_response', sa.Text(), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('analyses')
    op.drop_table('alerts')
    # ### end Alembic commands ###
